name: Publish-Package

on:
  issue_comment:
    types: [created, edited]

jobs:
  setup:
    name: Setup source
    if: >
      !github.event.issue.pull_request
      && contains(github.event.comment.body, 'Release')
      && contains(join(github.event.issue.labels.*.name, ', '), 'release')
      && contains(join(github.event.issue.labels.*.name, ', '), 'package:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

  comment:
    name: Create comment
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Create comment on issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{secrets.ACTION_TOKEN}}
          repository: tekuasia/blocks
          issue-number: ${{ github.event.issue.number }}
          body: Publishing ${{ steps.package-version.outputs.name}}:${{ steps.package-version.outputs.version }}

  publish:
    name: Publish
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Setup npm env
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > /home/runner/work/_temp/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: lerna exec --scope @teku-blocks/firebase -- npm  publish

  move:
    name: Move task to Released
    needs: [setup, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Auto Move
        uses: hungluu/move-tasks@v2
        with:
          actionToken: ${{ secrets.ACTION_TOKEN }}
          repository: tekuasia/blocks
          project: orgs/tekuasia/projects/5
          fromCards: >
            $project
              > columns(name is In progress, Merged)
              > cards(contentId is ${{ github.event.issue.id }})
          toColumn: $project > columns(name is Released)
